/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.Collection;
import java.util.OptionalDouble;


public class App {

    public static void main(String[] args) {
        Collection<Integer> edadesConsumidores = Arrays.asList(10,20,12,22,40,25,16,32);

        OptionalDouble promedioEdades = edadesConsumidores.stream()
            .filter(edad -> edad > 18)
            .mapToInt(Integer::intValue)
            .average();
        
        System.out.println(Math.round(promedioEdades.getAsDouble()));
    }
}
