/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.OptionalDouble;
import java.util.stream.Collector;
import java.util.stream.Collectors;


public class App {

    public static void main(String[] args) {
        Collection<Integer> numeros = Arrays.asList(501, 102, 65, 70, 23, 24, 1222, 300);

        List<Integer> numerosParesOrdenados = numeros.stream()
            .parallel()
            .filter(numero -> numero % 2 == 0)
            .sorted()
            .collect(Collectors.toList());
        
        System.out.println(numerosParesOrdenados);
    }
}
