server:
    port: 8080

---
spring:
  config:
    activate:
      on-profile: test_unitarios
  datasource:
    url: jdbc:h2:mem:test-db
    username: test-user
    password: test-pass

---
spring:
  config:
    activate:
      on-profile: funcional
  datasource:
    url: jdbc:postgresql://localhost:5432/inv-virtual
    username: usuario-taller5
    password: pass-taller5